-- E.
-- Create the tablespace PANDORA
CREATE TABLESPACE PANDORA
    ADD DATAFILE 'PANDORA.ibd'
    ENGINE = InnoDB;

-- Create database GESTMAT
CREATE DATABASE GESTMAT
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;
-- In MySQL it isn't possible to set a default tablespace. Any tables created in GESTMAT will need to specify the tablespace explicitly.

-- F. 
-- Create user TRANSFORMADOR_1 and grant necessary privileges
CREATE USER 'TRANSFORMADOR_1'@'localhost' IDENTIFIED BY 'password';

-- Grant privileges to create and insert data in GESTMAT database
GRANT CREATE, INSERT, SELECT, REFERENCES, INDEX, CREATE VIEW ON GESTMAT.* TO 'TRANSFORMADOR_1'@'localhost';
GRANT SELECT ON RAW_IMPORT.* TO 'TRANSFORMADOR_1'@'localhost';

-- Apply the privileges
FLUSH PRIVILEGES;

-- Now exit and enter with the new created account:
-- mysql> exit
-- C:\Program Files\MySQL\MySQL Server 8.0\bin>mysql -u TRANSFORMADOR_1 -p

USE GESTMAT;

-- G. Create the tables derived from the design analysis
CREATE TABLE AUTONOMOUS_COMMUNITIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    comunitat_autonoma VARCHAR(104) NOT NULL UNIQUE
) TABLESPACE PANDORA;

CREATE TABLE LOCATION (
    id INT AUTO_INCREMENT PRIMARY KEY,
    CP VARCHAR(8) NOT NULL,
    MUNICIPI VARCHAR(104) NOT NULL,
    community_id INT NOT NULL,
    FOREIGN KEY (community_id) REFERENCES AUTONOMOUS_COMMUNITIES(id),
    UNIQUE(CP, MUNICIPI, community_id)
) TABLESPACE PANDORA;

CREATE TABLE ISLANDS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    illa VARCHAR(104) NOT NULL UNIQUE
) TABLESPACE PANDORA;

CREATE TABLE COURSE_YEARS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    curs VARCHAR(48) NOT NULL UNIQUE
) TABLESPACE PANDORA;

CREATE TABLE EDUCATION_TYPES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipus_ensenyament VARCHAR(56) NOT NULL UNIQUE
) TABLESPACE PANDORA;

CREATE TABLE MODALITIES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    modalitat VARCHAR(56) NOT NULL UNIQUE
) TABLESPACE PANDORA;

CREATE TABLE CENTRE_TYPES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    DENOMINACIO_GENERICA VARCHAR(104) NOT NULL UNIQUE
) TABLESPACE PANDORA;

CREATE TABLE OWNERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    TITULAR VARCHAR(256) NOT NULL UNIQUE
) TABLESPACE PANDORA;

CREATE TABLE CENTRES (
    CODI VARCHAR(24) PRIMARY KEY,
    type_id INT NOT NULL,
    NOM VARCHAR(256) NOT NULL,
    CORREU_ELECTRONIC_1 VARCHAR(256),
    CORREU_ELECTRONIC_2 VARCHAR(256),
    PAGINA_WEB VARCHAR(256),
    owner_id INT NOT NULL,
    NIF VARCHAR(24) NOT NULL,
    LOCALITAT VARCHAR(256) NOT NULL,
    ADRECA VARCHAR(256) NOT NULL,
    location_id INT NOT NULL,
    island_id INT NOT NULL,
    TELEF1 VARCHAR(16),
    FOREIGN KEY (type_id) REFERENCES CENTRE_TYPES(id),
    FOREIGN KEY (owner_id) REFERENCES OWNERS(id),
    FOREIGN KEY (location_id) REFERENCES LOCATION(id),
    FOREIGN KEY (island_id) REFERENCES ISLANDS(id)
) TABLESPACE PANDORA;

CREATE TABLE STUDENTS (
    dni VARCHAR(24) PRIMARY KEY,
    nom VARCHAR(256) NOT NULL,
    primer_cognom VARCHAR(256) NOT NULL,
    segon_cognom VARCHAR(256),
    correu_electronic VARCHAR(256) NOT NULL, -- Should be unique but because of the data provided duplicate mails exists
    districte VARCHAR(24) NOT NULL,
    location_id INT NOT NULL,
    FOREIGN KEY (location_id) REFERENCES LOCATION(id)
) TABLESPACE PANDORA;

CREATE TABLE SUBJECTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom_assignatura VARCHAR(256) NOT NULL,
    education_type_id INT NOT NULL,
    modality_id INT NOT NULL,
    course_year_id INT NOT NULL,
    FOREIGN KEY (education_type_id) REFERENCES EDUCATION_TYPES(id),
    FOREIGN KEY (modality_id) REFERENCES MODALITIES(id),
    FOREIGN KEY (course_year_id) REFERENCES COURSE_YEARS(id),
    UNIQUE(nom_assignatura, education_type_id, modality_id, course_year_id)
) TABLESPACE PANDORA;

CREATE TABLE ENROLLMENTS (
    dni VARCHAR(24),
    subject_id INT,
    codi_centre VARCHAR(24),
    grup_de_classe VARCHAR(56),
    PRIMARY KEY (dni, subject_id, codi_centre, grup_de_classe),
    FOREIGN KEY (dni) REFERENCES STUDENTS(dni),
    FOREIGN KEY (subject_id) REFERENCES SUBJECTS(id),
    FOREIGN KEY (codi_centre) REFERENCES CENTRES(CODI)
) TABLESPACE PANDORA;